# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
  rev: v1.2.0
  hooks:
  - id: mix-format
  - id: mix-test
- repo: local
  hooks:
  - id: mix-credo
    name: mix credo
    description: Runs Elixir credo checks with mix credo.
    entry: mix credo
    language: system
    files: \.ex$
